DROP TABLE VOL CASCADE CONSTRAINTS;
DROP TABLE TERMINAL CASCADE CONSTRAINTS;
DROP TABLE AEROPORT CASCADE CONSTRAINTS;
DROP TABLE VILLE CASCADE CONSTRAINTS;
DROP TABLE PAYS CASCADE CONSTRAINTS;
DROP TABLE COMPAGNIE CASCADE CONSTRAINTS;
